export const ROUTES = {
  auth: {
    login: "/auth/login",
    signup: "/auth/signup",
    me: "/auth/me",
  },
  conversations: {
    contacts: "/conversations/contacts",
    contactInfo: (id: number) => `/conversations/${id}/contact-info`,
    markAsRead: (id: number) => `/conversations/${id}/read`,
    archive: (id: number) => `/conversations/${id}/archive`,
    unarchive: (id: number) => `/conversations/${id}/unarchive`,
    deleteBulk: "/conversations/bulk",
  },
  aiAssistant: {
    config: "/ai-assistant/config",
    autoReplyStatus: "/ai-assistant/auto-reply/status",
    autoReplyEnable: "/ai-assistant/auto-reply/enable",
    testReply: "/ai-assistant/test-reply",
    translate: "/ai-assistant/translate",
    suggestedReplies: (conversationId: number) =>
      `/ai-assistant/conversations/${conversationId}/suggested-replies`,
  },
  knowledge: {
    upload: "/knowledge/upload",
    ask: "/knowledge/ask",
    files: "/knowledge/files",
    clear: "/knowledge/clear",
  },
  messages: {
    telegramReply: "/telegram/reply",
    whatsappReply: "/whatsapp/reply",
    messengerReply: "/messenger/reply",
    emailReply: "/email/reply",
  },
  platforms: {
    accounts: "/platform-accounts",
    telegramConnect: "/telegram/connect",
    whatsappConnect: "/whatsapp/connect",
    facebookConnect: "/integrations/facebook/connect",
    facebookPendingPages: "/integrations/facebook/pending-pages",
    facebookSelectPage: "/integrations/facebook/select-page",
    facebookStatus: "/integrations/facebook/status",
    facebookDisconnect: "/integrations/facebook/disconnect",
    emailConnect: "/email/connect",
    emailDisconnect: (email: string) => `/email/disconnect/${encodeURIComponent(email)}`,
    emailTest: (email: string) => `/email/test/${encodeURIComponent(email)}`,
    emailAccounts: "/email/accounts",
  },
  analytics: {
    tokens:   "/analytics/tokens",
    cost:     "/analytics/cost",
    messages: "/analytics/messages",
  },
} as const;
